//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RishonimEntities : DbContext
    {
        public RishonimEntities()
            : base("name=RishonimEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Food1> Food1 { get; set; }
        public virtual DbSet<DividersPerNumber> DividersPerNumbers { get; set; }
        public virtual DbSet<Search> Searches { get; set; }
    
        public virtual int add_search(Nullable<int> number, string gormim)
        {
            var numberParameter = number.HasValue ?
                new ObjectParameter("Number", number) :
                new ObjectParameter("Number", typeof(int));
    
            var gormimParameter = gormim != null ?
                new ObjectParameter("Gormim", gormim) :
                new ObjectParameter("Gormim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("add_search", numberParameter, gormimParameter);
        }
    
        public virtual ObjectResult<get_dividers_per_number_Result> get_dividers_per_number()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_dividers_per_number_Result>("get_dividers_per_number");
        }
    
        public virtual ObjectResult<Nullable<int>> get_searches_count_equal_number()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("get_searches_count_equal_number");
        }
    
        public virtual ObjectResult<get_searches_from_date_Result> get_searches_from_date(string conterOverTwenty)
        {
            var conterOverTwentyParameter = conterOverTwenty != null ?
                new ObjectParameter("ConterOverTwenty", conterOverTwenty) :
                new ObjectParameter("ConterOverTwenty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_searches_from_date_Result>("get_searches_from_date", conterOverTwentyParameter);
        }
    
        public virtual ObjectResult<get_searches_over_Twenty_Result> get_searches_over_Twenty()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_searches_over_Twenty_Result>("get_searches_over_Twenty");
        }
    }
}
